#!/usr/bin/env bash

set -euo pipefail


function test_modified_folders(){
  local modified_files=$(git status --short --porcelain | grep -v "??" | awk '{print $2}') # -v ??: remove untracked #^M means modified AND staged. ^ M means modified BUT NOT added
  set +e
  local folders=$(echo $modified_files | xargs -l dirname 2>/dev/null | sort | uniq) # Allow to fail silently if no folder has been modified
  set -e

  echo "$folders" | while read folder; do
    if [ -f "$folder/CMakeLists.txt" ]; then
      cmake .. "$folder/cmake-build-debug"
      make -C "$folder/cmake-build-debug" all test
    fi
  done
}

test_modified_folders

